syntax on

if has("autocmd")
    " Jump to last open
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
    "Indentation rules for language
    filetype plugin indent on
endif
if has("gui_running")
    set guifont=Fantasque\ Sans\ Mono\ 10
endif

"Base vim setup
set showcmd
set showmatch
set ignorecase
set smartcase
set wrap
set tabstop=4
set backspace=indent,eol,start
set autoindent
set copyindent
set shiftwidth=4
set number
set expandtab
set title
set noerrorbells
filetype plugin on


"work specific
command! Sync :!~/up.sh


"==>all fancy plugin/magic stuff<==
if has('nvim')
    "work around for mouse selection to clipboard
    vnoremap <LeftRelease> "*ygv

    call plug#begin('~/.local/share/nvim/plugged')
else
    call plug#begin('~/.vim/plugged')
endif
"github pluugins
Plug 'junegunn/vim-easy-align'
Plug 'neomake/neomake'
Plug 'vim-airline/vim-airline'
Plug 'tpope/vim-surround'
Plug 'scrooloose/nerdtree'
call plug#end()

"[NerdTree]
set encoding=utf-8
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 1
let g:NERDTreeDirArrows=0
map <C-n> :NERDTreeFocus<CR>


"[Easy Align]
" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)
" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)


"[Airline]
set laststatus=2

"[NeoMake]
autocmd! BufWritePost * Neomake

let g:neomake_javascript_jshint_maker = {
    \ 'args': ['--verbose'],
    \ 'errorformat': '%A%f: line %l\, col %v\, %m \(%t%*\d\)',
    \ }
let g:neomake_javascript_enabled_makers = ['jshint']

"just in case the transparent background doesnt set at the bottom
set background=dark
"mmmh so nice
colorscheme molokai
"nice transparent background
hi Normal ctermbg=NONE
hi Search ctermfg=black ctermbg=white

